test: XrpCurrencyAmount tests
XRPLF/xrpl4j pull request #201
Opened 2021-12-10 20:30 UTC by mukulljangid

Add tests for class XrpCurrencyAmount

2021-12-10 20:57 UTC, sappenin commented
Fixes #73

2021-12-10 20:58 UTC, sappenin requested changes

2021-12-10 20:58 UTC, sappenin commented on xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/transactions/XrpCurrencyAmountTest.java
> +    assertThat(
Can we add a unit test to cover the case where subtraction yields a negative number?

2021-12-10 21:00 UTC, sappenin commented on xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/transactions/XrpCurrencyAmountTest.java
>    }
Let's also add coverage of the `toString()` method.

2021-12-10 22:03 UTC, nkramer44 commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java
> +    static final long TWO_XRP_IN_DROPS = 2_000_000L;
Can we move this to the test class if it's not used elsewhere?

2021-12-10 22:05 UTC, nkramer44 requested changes

2021-12-10 22:05 UTC, nkramer44 commented on xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/transactions/XrpCurrencyAmountTest.java
> +      XrpCurrencyAmount.ofXrp(XrpCurrencyAmount.ofDrops(1L).toXrp())
Couldn't you just do `XrpCurrencyAmount.ofDrops(1L)`?

2021-12-16 19:17 UTC, nkramer44 approved these changes

2021-12-17 00:58 UTC, sappenin approved these changes

2021-12-17 00:59 UTC, merged