Add pseudo-transactions
XRPLF/xrpl4j pull request #234
Opened 2022-03-10 00:00 UTC by mukulljangid

Add pseudo-transactions:

- SetFee
- EnableAmendment
- UNLModify

Add tests.

2022-03-13 18:10 UTC, sappenin requested changes
All looks good, just one request around testing.

2022-03-13 18:10 UTC, sappenin commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/TransactionType.java
> +  ENABLE_AMENDMENT("EnableAmendment"),
Can you add Unit tests that assert the capitalization and contents of each value in this class (i.e., in `TransactionType`)?

2022-03-13 18:10 UTC, sappenin commented on xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/transactions/EnableAmendmentTest.java
> +  public void testJson() throws JsonProcessingException, JSONException {
This test doesn't appear to be testing any JSON.  Let's rename the test to something clearer, like this:

```suggestion
  public void testBuilder() throws JsonProcessingException, JSONException {
```

2022-03-13 18:10 UTC, sappenin commented on xrpl4j-model/src/test/java/org/xrpl/xrpl4j/model/transactions/SetFeeTest.java
> +  public void testJson() throws JsonProcessingException, JSONException {
This test doesn't appear to be testing any JSON.  Let's rename the test to something clearer, like this:

```suggestion
  public void testBuilder() throws JsonProcessingException, JSONException {
```

2022-03-16 13:58 UTC, nkramer44 approved these changes
This looks great. Thanks for thinking through this one and nice job figuring out the serializer stuff!

2022-03-17 20:55 UTC, mukulljangid commented
@sappenin @nkramer44 Also, this would help us in future, when we introduce FeeSettings ledger object. FeeSettings also has the field, BaseFee, which is also expected to be in hex, so this serializer change will help us there in future.

2022-03-26 14:25 UTC, sappenin approved these changes
LGTM!

2022-03-26 14:25 UTC, merged