add metadata alias in TransactionResult
XRPLF/xrpl4j pull request #241
Opened 2022-03-14 19:43 UTC by mukulljangid

fixes https://github.com/XRPLF/xrpl4j/issues/239

2022-03-16 13:56 UTC, sappenin requested changes
I think this will work, but let's add some unit test coverage to validate the fix.

2022-03-21 21:54 UTC, nkramer44 requested changes
Just one small nit then this is good!

2022-03-21 21:54 UTC, nkramer44 commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/LedgerResultIT.java
> +        .transactions(true)
can you reformat these lines so they are lined up?

2022-03-22 23:12 UTC, sappenin approved these changes
LGTM!

2022-03-22 23:17 UTC, nkramer44 approved these changes

2022-03-22 23:21 UTC, merged