constants for TransactionResult codes
XRPLF/xrpl4j pull request #253
Opened 2022-04-04 21:45 UTC by mukulljangid

Addresses #77

2022-04-05 18:08 UTC, nkramer44 requested changes

2022-04-05 18:08 UTC, nkramer44 commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/TransactionResultCode.java
> +public class TransactionResultCode {
Small nit, but can we rename this to `TransactionResultCodes`? Usually when you have a class that just contains a bunch of static methods, the class name is plural. The Guava library does this a lot, like `Strings`, `Lists`, `Maps` etc

2022-04-12 19:45 UTC, sappenin requested changes

2022-04-12 19:45 UTC, sappenin commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/TransactionResultCodes.java
> +public class TransactionResultCodes {
Per our discussion, let's make a unit test for this one.

2022-04-13 00:24 UTC, sappenin approved these changes

2022-04-13 15:11 UTC, sappenin approved these changes

2022-04-13 15:12 UTC, merged