sort signers in the encoder and add test to verify hash
XRPLF/xrpl4j pull request #257
Opened 2022-04-19 15:11 UTC by mukulljangid

Rippled expects signers to be sorted by address as a part of submit_multisigned.
This PR sorts the list of signers in the encoder right before serializing it.

2022-04-19 15:30 UTC, nkramer44 requested changes
Looks good! Just a couple of comments.

Also, can you try to add some tests to `BinarySerializationTests` with signers in order and out of order?

2022-04-19 15:58 UTC, sappenin requested changes

2022-04-19 15:58 UTC, sappenin commented on xrpl4j-binary-codec/src/main/java/org/xrpl/xrpl4j/codec/binary/types/STObjectType.java
> +        List<JsonNode> jsonNodeList = new ArrayList<>();
We need unit test coverage of this in addition to the ITs...that codecov tool in IDEA is your friend! :)

2022-04-19 22:54 UTC, sappenin approved these changes

2022-04-20 14:31 UTC, nkramer44 approved these changes

2022-04-27 20:50 UTC, merged