Introduce class `FeeUtils` with dynamic fee calculation function
XRPLF/xrpl4j pull request #260
Opened 2022-04-28 19:39 UTC by mukulljangid

Adds `FeeUtils` class:

- Moving computeMultiSigFee() from Transaction model to this utils class [Breaking change]
- Adds new calculateFeeDynamically() to fluctuate on the basis of load on rippled.

2022-04-28 19:43 UTC, mukulljangid commented
Lets discuss if this logic makes sense to you all and then I can add tests.

Ref: https://gist.github.com/WietseWind/3e9f9339f37a5881978a9661f49b0e52

2022-04-29 18:19 UTC, sappenin requested changes

2022-04-29 18:19 UTC, sappenin commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/client/fees/FeeUtils.java
> +  public static XrpCurrencyAmount calculateFeeDynamically(FeeResult feeResult) {
We need unit tests on this method. See Codecov warnings below.

2022-04-29 18:19 UTC, sappenin commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/client/fees/FeeUtils.java
> +  public static XrpCurrencyAmount computeMultiSigFee(
We need unit tests on this method. See Codecov warnings below.

2022-05-02 14:27 UTC, nkramer44 requested changes

2022-05-02 14:27 UTC, nkramer44 commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/client/fees/FeeUtils.java
> +    int queuePct = currentQueueSize / maxQueueSize;
It's almost always better to use full words in variable names, so this should be `queuePercentage` I think

2022-05-02 14:27 UTC, nkramer44 commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Transaction.java
> -  }
This needs to stay here until we release v3, otherwise this is a breaking change. Let's `@Deprecated` this instead

2022-06-02 00:23 UTC, sappenin requested changes
My mistake -- was looking at a commit and thought it was a different PR.

2022-06-07 20:41 UTC, nkramer44 approved these changes
Approving so I don't block, but please fix the javadoc formatting before merging

2022-06-07 20:41 UTC, nkramer44 commented on xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Transaction.java
> +   * org.xrpl.xrpl4j.model.client.transactions.TransactionResult#closeDate()};
This formatting looks off to me. Continuations in javadocs should have 2 spaces at the beginning of the line

2022-06-08 20:14 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/SignerListSetIT.java
> -          feeResult.drops().openLedgerFee(),
This is fixed.

2022-06-08 20:14 UTC, sappenin approved these changes

2022-06-21 22:08 UTC, merged