Add support for featureDisallowIncoming amendment
XRPLF/xrpl4j pull request #419
Opened 2023-06-13 19:33 UTC by nkramer44

This PR adds support for the `DisallowIncoming` amendment that was recently activated on mainnet. See [this PR](https://github.com/XRPLF/rippled/pull/4336) for more details on the amendment.

2023-06-14 15:06 UTC, sappenin requested changes
Two minor questions.

2023-06-20 15:21 UTC, nkramer44 commented on xrpl4j-core/src/test/java/org/xrpl/xrpl4j/model/flags/AccountRootFlagsTests.java
> +  @SuppressWarnings("AbbreviationAsWordInName")
I think there is only one `of` method on `AccountRootFlags` (`of(long flags)`)? That should be tested by this line:
```
AccountRootFlags flags = AccountRootFlags.of(expectedFlags);
```

2023-06-21 19:21 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountTransactionsIT.java
> +
Let's add a link to the clio GH issue that fixes the 748 vs 752 bug.

2023-06-21 19:27 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/environment/MainnetEnvironment.java
> +  //  "ledger_index" = "validated", which breaks AccountTransactionsIT. xrplcluster.com is not powered by Clio, so
Let's do the following:

1. Break `TestnetEnvironment` into two: `ReportingTestnetEnvironment` (points to https://s.altnet.rippletest.net:51234) and `ClioTestnetEnvironment` (points to https://clio.altnet.rippletest.net:51234).
2. In CI, run all ITs against both environments.
3. If the ClioTestnet environment fails, we'll log a bug in Clio, but merge xrp4lj PRs (i.e., clio tests are not required to pass).

2023-06-21 19:28 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/environment/MainnetEnvironment.java
> +  private final XrplClient xrplClient = new XrplClient(HttpUrl.parse("https://xrplcluster.com"));
Let's also run against this environment in CI as well.

2023-06-21 19:29 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountTransactionsIT.java
> +    results.transactions().forEach(transaction -> transactionHashes.add(transaction.resultTransaction().hash()));
Per discussion with @nkramer44, we'll revert this back to the original and per the comments below -- this test will run against a variety of additional environments.

2023-06-22 20:33 UTC, sappenin commented on xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/environment/MainnetEnvironment.java
> - * ========================LICENSE_START=================================
Let's put this license back?

2023-06-26 22:39 UTC, sappenin approved these changes

2023-06-27 14:23 UTC, merged